[install]
is_configured = 0
state = enabled
build = 1

[id]
name = TA-posthog-activity-logs
version = 0.1.0

[ui]
is_visible = 1
label = PostHog activity logs

[launcher]
author = PostHog
description = Collect PostHog activity logs as OCSF events for security monitoring and compliance. Having issues with PostHog's add-on? Ping us at https://us.posthog.com/#panel=support:support:platform_addons:medium and we'll get it sorted for you.
version = 0.1.0

[package]
id = TA-posthog-activity-logs
